### PR TITLE
Time utils fix

### LINKED ISSUE #402: Bad floating point cast to integer in time conversion utils
To convert from nanoseconds to milliseconds, which are both stored as integer types, we are multiplying by `0.000001` and then casting to an integer. But this means that they are losing precision and then getting inappropriately truncated. For example, `0.2 s`, aka `200000000 ns` gets truncated to `199 ms`, `0.3 s` gets truncated to `299` ms, etc. 

We should just need to change it to integer division instead of floating point multiplication. 

The problem is in at least two spots

https://github.com/Yaskawa-Global/motoros2/blob/48d71146fb055c6a71d037abb0014d2f3cfa2031/src/TimeConversionUtils.h#L15-L18

https://github.com/Yaskawa-Global/motoros2/blob/48d71146fb055c6a71d037abb0014d2f3cfa2031/src/TimeConversionUtils.h#L37-L40

This may only matter if the duration or timestamp falls right on a whole millisecond value.

### PR DESCRIPTION
**Pull request by jimmy-mcelwain**
Resolves #402

This PR gets rid of the floating point math error that results in inappropriate truncation of ms timestamps. 

It also changes the time utils to work for negative times and negative durations. 

I added a bunch of unit tests. Note that due the problem discussed in #407, the controller will crash if you set the testing flag. So make sure to comment out [these lines](https://github.com/Yaskawa-Global/motoros2/blob/ec13454105c21c9397449f9aa1491a224147cc14/src/main.c#L75-L78) before setting that flag and building. 

This PR is a lot more broad than I was originally planning on it being, mostly because dealing with negative times/durations is more inconvenient than I originally thought. I'm happy to make changes though.

### CODE REVIEW

File: src/Tests_TestUtils.c [hunk 1]
```diff
@@ -30,4 +30,32 @@ BOOL Ros_Testing_CompareLong(long a, long b)
     return ok;
 }
 
+BOOL Ros_Testing_CompareINT64(INT64 a, INT64 b)
```
Comment (gavanderhoorn) [inline src/Tests_TestUtils.c:33]: Should we rename this to indicate it actually checks for *equality*?

I realise the existing functions follow a similar naming scheme, but we can take this opportunity to introduce more aptly named functions already (and address renaming the others at a later time).

File: src/Tests_TestUtils.c [hunk 2]
```diff
@@ -30,4 +30,32 @@ BOOL Ros_Testing_CompareLong(long a, long b)
...
+{
+    BOOL ok = a == b;
+
+    if (!ok)
+        Ros_Debug_BroadcastMsg("Fail: %lld != %lld", a, b);
+
+    return ok;
+}
+
+BOOL Ros_Testing_CompareTimespec(const struct timespec* lhs, const struct timespec* rhs)
```
Comment (gavanderhoorn) [inline src/Tests_TestUtils.c:43]: Same here.

File: src/Tests_TimeConversionUtils.h [hunk 3]
```diff
@@ -0,0 +1,17 @@
+// Tests_TimeConversionUtils.h
+
+// SPDX-FileCopyrightText: 2023, Yaskawa America, Inc.
+// SPDX-FileCopyrightText: 2023, Delft University of Technology
```
Comment (gavanderhoorn) [inline src/Tests_TimeConversionUtils.h:4]:
```suggestion
// SPDX-FileCopyrightText: 2025, Yaskawa America, Inc.
// SPDX-FileCopyrightText: 2025, Delft University of Technology
```

File: src/TimeConversionUtils.h [hunk 4]
```diff
@@ -11,56 +11,76 @@
...
+        *quotient -=  1;
+    }
+
+    *remainder = abs(dividend - *quotient * divisor);
+}
 
 static inline INT64 Ros_Duration_Msg_To_Millis(builtin_interfaces__msg__Duration const* const x)
 {
-    return ((INT64)x->sec * 1000) + (INT64)(x->nanosec * 0.000001);
+    return (x->sec * 1000LL) + (x->nanosec / (1000LL * 1000LL));
```
Comment (gavanderhoorn) [inline src/TimeConversionUtils.h:28]: I like the fact you used two `1000LL` (instead of `1000000LL`). Would `1e6` also work?

Perhaps more a comment below, where it would become `1e9`.

Comment (jimmy-mcelwain) [reply src/TimeConversionUtils.h:28]: I thought about that, but thought I would just keep everything that I could in the integer space. I figured with the casting that would be needed to avoid floating point math, it wouldn't be much simpler that way but I recognize the way it is now is messy. I could switch to scientific notation with casts before any math happens, I think that should be fine.

**Comment by jimmy-mcelwain** [comment]
The first round of suggestions have all been addressed

**Comment by ted-miller** [comment]
Looks good to me. But I haven't tried to run it yet. I'm assuming that #412 should be done first.

**Comment by jimmy-mcelwain** [comment]
> Looks good to me. But I haven't tried to run it yet. I'm assuming that https://github.com/Yaskawa-Global/motoros2/pull/412 should be done first.

It would probably make more sense that way

**Review by ted-miller — APPROVED** [review]
> Looks good to me. But I haven't tried to run it yet. I'm assuming that https://github.com/Yaskawa-Global/motoros2/pull/412 should be done first.

I just validated by commenting out the other test-routines.

**Comment by gavanderhoorn** [comment]
Thanks for the changes @jimmy-mcelwain :+1:
