### PR TITLE
Fixed Cryptic Error Codes in mpStartJob

### LINKED ISSUE #102: Cryptic error codes from mpStartJob
When enabling a motion mode, the software tries to start the INFORM job. If it fails to start that job, it returns a cryptic error code. You would need to reference the MotoPlus documentation to find the definition. 

Ex: `Can't start 'INIT_ROS' because: 0x3040`

We should map the error codes to a lookup table with human-readable strings.

```
0x0000 Normal end
0x2010 Robot is in operation
0x2030 In HOLD status (PP)
0x2040 In HOLD status (External)
0x2050 In HOLD status (Command)
0x2060 In error/alarm status
0x2070 In SERVO OFF status
0x2080 Wrong operation mode
0x3040 The home position is not registered
0x3050 Out of range (ABSO data)
0x3400 Cannot operate MASTER JOB
0x3410 The JOB name is already registered in another task.
0x4040 Specified JOB not found
```

### PR DESCRIPTION
**Pull request by aigallegos**
fixes #102. I wrote a new function that kept the error string format as an f-string for mpStartJob errors in MotionControl.c by just adding a new function called Ros_ErrorHandling_Only_ErrNo_ToString in ErrorHandling.c that did not use strncpy and therefore did not need a buffer to get passed in, similar to Ros_ErrorHandling_MotionNotReadyCode_ToString it just returns a char* instead of having a destination for the chars and can be directly passed into the error f-string.

### CODE REVIEW

File: src/ErrorHandling.c [hunk 1]
```diff
@@ -32,6 +32,41 @@ void Ros_ErrorHandling_ErrNo_ToString(int errNo, char* const errMsg, int errMsgS
     }
 }
 
+const char* const Ros_ErrorHandling_Only_ErrNo_ToString(int errNo)
```
Comment (gavanderhoorn) [inline src/ErrorHandling.c:35]: This seems to duplicate what `Ros_ErrorHandling_ErrNo_ToString(..)` does above. It also appears to return pointers to temporary objects.

Could we use `Ros_ErrorHandling_ErrNo_ToString(..)` instead of adding a new function?

File: src/MotionControl.c [hunk 2]
```diff
@@ -1287,7 +1287,7 @@ BOOL Ros_MotionControl_StartMotionMode(MOTION_MODE mode)
     {
         //TODO(gavanderhoorn): special check for "job is not loaded"
         Ros_Debug_BroadcastMsg(
-            "Can't start '%s' because: 0x%04X", g_nodeConfigSettings.inform_job_name, rData.err_no);
+            "Can't start '%s' because: 0x%04X %s", g_nodeConfigSettings.inform_job_name, rData.err_no, Ros_ErrorHandling_Only_ErrNo_ToString(rData.err_no));
```
Comment (gavanderhoorn) [inline src/MotionControl.c:1290]: please see my https://github.com/Yaskawa-Global/motoros2/issues/102#issuecomment-1661579552.

I would suggest we replace the other case where we print `rData.err_no` directly as well.

**Review by gavanderhoorn — DISMISSED** [review]

**Comment by gavanderhoorn** [comment]
> I wrote a new function that kept the error string format as an f-string for mpStartJob errors in MotionControl.c by just adding a new function called Ros_ErrorHandling_Only_ErrNo_ToString in ErrorHandling.c that did not use strncpy and therefore did not need a buffer to get passed in

thing is, that buffer & copy are needed, as functions can't return pointers to temporaries (ie: variables on the stack).

> similar to Ros_ErrorHandling_MotionNotReadyCode_ToString it just returns a char* instead of having a destination for the chars and can be directly passed into the error f-string.

you could consider defining all error 'strings' as

```c
static char something[] = "...";
```

which would allow just `return`-ing `something` directly.

`Ros_ErrorHandling_MotionNotReadyCode_ToString(..)` used to do this, but that's invisible now, as the storage for the 'strings' returned by it is the responsibility of the code generated by the ROS 2 message generators now.

File: src/ErrorHandling.c (hunk 1 above)
Comment (aigallegos) [reply src/ErrorHandling.c:35]: Sure! I just had though you wanted it to function similarly to `Ros_ErrorHandling_MotionNotReadyCode_ToString(..)` and return a temporary object which `Ros_ErrorHandling_ErrNo_ToString(..)` does not do. What should the object that should be the destination (the 2nd parameter) that is passed into `Ros_ErrorHandling_ErrNo_ToString(..)` be? Can I create a new buffer specifically for this?

Comment (gavanderhoorn) [reply src/ErrorHandling.c:35]: > Sure! I just had though you wanted it to function similarly to `Ros_ErrorHandling_MotionNotReadyCode_ToString(..)` and return a temporary object which `Ros_ErrorHandling_ErrNo_ToString(..)` does not do. 

`Ros_ErrorHandling_MotionNotReadyCode_ToString(..)` does not return a pointer-to-temporary. It returns the `const char*` which points to a `static`ally allocated string inside the type support library for `motoros2_interface`.

As follows (from `target_ws\install\include\motoros2_interfaces\msg\detail\motion_ready_enum__struct.h`, generated code):

<details><summary>Click to expand</summary>

```c
// Constants defined in the message

/// Constant 'READY'.
/**
  * Result codes which may be returned by services and actions which attempt to
  * execute motion (or are executing motion).
  *
  * Values other than 1 would indicate an active error or other active inhibition
  * on the Yaskawa controller preventing MotoROS2 from enabling trajectory mode
  * or executing any motion.
  *
  * Applications are encouraged to refer to the named constants generated by
  * rosidl as part of this message instead of using the integer values directly.
 */
enum
{
  motoros2_interfaces__msg__MotionReadyEnum__READY = 1
};

/// Constant 'READY_STR'.
static const char * const motoros2_interfaces__msg__MotionReadyEnum__READY_STR = "Ready";

...
```

</details>

The `static` there changes the lifetime of the strings to essentially `as-long-as-the-program-runs`.

> What should the object that should be the destination (the 2nd parameter) that is passed into `Ros_ErrorHandling_ErrNo_ToString(..)` be? Can I create a new buffer specifically for this?

There are two options I believe:

 1. you just use `Ros_ErrorHandling_ErrNo_ToString(..)` as-is. That would mean you'd have to provide a `char[]` for the `strncpy(..)` to copy into.
 2. we could change `Ros_ErrorHandling_ErrNo_ToString(..)` to also have it return `const char*` to `static`ally allocated strings. That should solve the issue identified here. `Ros_ErrorHandling_ErrNo_ToString(..)` is not currently used, so it would be a relatively minor change without too much fall-out.

I'll push a commit which implements option 2.

**Comment by gavanderhoorn** [comment]
Note: we should consider squash-merging this if possible. All my commits are essentially fix-ups.

**Review by ted-miller — APPROVED** [review]
Looks good.

```
THU 2023-08-03 15:03:27.596 Ros_MotionControl_StartMotionMode: enter
THU 2023-08-03 15:03:29.876 Can't start 'INIT_ROS' because: 'The home position is not registered' (0x3040)
```

Thank you both for the PR!

**Comment by gavanderhoorn** [comment]
Thanks @aigallegos 👍

**Comment by aigallegos** [comment]
> Thanks @aigallegos 👍

Thank YOU! I learned so much from this rabbit hole we went down and thanks for putting up with my newbie negligence that just so happened to be correct haha. Thanks for the help and happy coding!

**Comment by gavanderhoorn** [comment]
If you see any other issues you believe you could help with, please comment on them and we can discuss potential approaches.
